import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import pc from "picocolors";
import { runHook } from "../hooks/runner.ts";
import { resolveChatRef } from "../resolve/chat-ref.ts";
import { indexClaudeArchive } from "../scan/indexer.ts";
import { getChat, markChatDone } from "../storage/repositories/chats.ts";

export interface ChatDoneOptions {
  status: string;
  summary: string;
  logDir?: string;
  outcomes?: string[];
  openItems?: string[];
  json?: boolean;
}

export async function runChatDone(ref: string, opts: ChatDoneOptions): Promise<void> {
  indexClaudeArchive();
  const uuid = resolveChatRef(ref);
  if (uuid === null) {
    process.stderr.write(`${pc.red("error:")} chat not found: ${ref}\n`);
    process.exit(1);
  }
  const chat = getChat(uuid);
  if (chat === null) {
    process.stderr.write(`${pc.red("error:")} chat not found: ${ref}\n`);
    process.exit(1);
  }
  if (opts.summary.trim().length === 0) {
    process.stderr.write(`${pc.red("error:")} --summary cannot be empty\n`);
    process.exit(1);
  }

  // Determine log directory: chat cwd / session-logs/ unless --log-dir overrides.
  const baseDir =
    opts.logDir ??
    (chat.cwd !== null && chat.cwd.length > 0
      ? join(chat.cwd, "session-logs")
      : join(process.cwd(), "session-logs"));

  if (!existsSync(baseDir)) {
    mkdirSync(baseDir, { recursive: true });
  }

  const today = new Date().toISOString().slice(0, 10);
  const slug = makeSlug(opts.summary);
  const filename = `${today}-${slug}.md`;
  const logPath = join(baseDir, filename);

  const log = renderSessionLog(chat, opts, today);
  writeFileSync(logPath, log, "utf-8");

  markChatDone(uuid, {
    status: opts.status,
    summary: opts.summary,
    logPath,
  });

  // Run post-touchdown hook
  const hook = runHook(
    "post-touchdown.sh",
    {
      STARSOS_CHAT_UUID: uuid,
      STARSOS_CHAT_CWD: chat.cwd ?? "",
      STARSOS_PROJECT_SLUG: chat.projectSlug ?? "",
      STARSOS_PROJECT_PATH: chat.cwd ?? "",
      STARSOS_TOUCHDOWN_LOG: logPath,
      STARSOS_TOUCHDOWN_SUMMARY: opts.summary,
      STARSOS_TOUCHDOWN_STATUS: opts.status,
    },
    { wait: true, verbose: true },
  );

  if (opts.json === true) {
    process.stdout.write(
      `${JSON.stringify({
        uuid,
        logPath,
        status: opts.status,
        summary: opts.summary,
        hookRan: hook.ran,
        hookExitCode: hook.exitCode,
      })}\n`,
    );
    return;
  }

  process.stdout.write(`${pc.green("✓")} touchdown logged for ${uuid.slice(0, 8)}\n`);
  process.stdout.write(`  ${pc.dim("→ session log:")} ${logPath}\n`);
  process.stdout.write(`  ${pc.dim("→ chat status:")} ${pc.bold("done")}\n`);
  if (hook.ran) {
    if (hook.exitCode === 0) {
      process.stdout.write(`  ${pc.dim("→ post-touchdown.sh hook:")} ${pc.green("ok")}\n`);
    } else {
      process.stdout.write(
        `  ${pc.dim("→ post-touchdown.sh hook:")} ${pc.yellow(`exit ${hook.exitCode}`)}\n`,
      );
    }
  }
}

function makeSlug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function renderSessionLog(
  chat: { uuid: string; cwd: string | null; title: string | null; projectSlug: string | null },
  opts: ChatDoneOptions,
  today: string,
): string {
  const project = chat.projectSlug ?? basename(chat.cwd ?? "") ?? "?";
  const lines: string[] = [];
  lines.push(`# Session ${today} — ${opts.summary}`);
  lines.push("");
  lines.push(`**Status**: ${opts.status}`);
  lines.push(`**Chat**: ${chat.uuid}`);
  lines.push(`**Project**: ${project}`);
  if (chat.cwd !== null) lines.push(`**cwd**: ${chat.cwd}`);
  if (chat.title !== null) lines.push(`**Original title**: ${chat.title}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(opts.summary);
  lines.push("");
  if (opts.outcomes !== undefined && opts.outcomes.length > 0) {
    lines.push("## Outcomes");
    lines.push("");
    for (const o of opts.outcomes) lines.push(`- ${o}`);
    lines.push("");
  }
  if (opts.openItems !== undefined && opts.openItems.length > 0) {
    lines.push("## Open Items");
    lines.push("");
    for (const i of opts.openItems) lines.push(`- [ ] ${i}`);
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("_Generated by Stars OS `chat done`._");
  return lines.join("\n");
}
